# SPDX-FileCopyrightText: 2025 2025 Oxyde Contributors
#
# SPDX-License-Identifier: MPL-2.0
[package]
name = "oxyde_compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
oxyde_panel     = { path = "../panel" }
oxyde_theming   = { path = "../theming" }
oxyde_oxynotify = { path = "../oxynotify" }
oxyde_oxymenu   = { path = "../oxymenu" }
oxyde_oxykeys   = { path = "../oxykeys" }
oxyde_oxyconfig = { path = "../oxyconfig" }
oxyde_launcher  = { path = "../launcher" }
oxyde_expose    = { path = "../expose" }
oxyde_dock      = { path = "../dock" }

smithay = { version = "0.7", features = ["backend_winit", "use_system_lib"], default-features = true }
calloop = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
anyhow = "1"

[[bin]]
name = "compositor"
path = "src/main.rs"
