# SPDX-FileCopyrightText: 2025 2025 Oxyde Contributors
#
# SPDX-License-Identifier: MPL-2.0

[workspace]
members = [
  "crates/compositor",
  "crates/panel",
  "crates/dock",
  "crates/expose",
  "crates/launcher",
  "crates/oxykeys",
  "crates/oxymenu",
  "crates/oxynotify",
  "crates/oxyconfig",
  "crates/theming", 
]
resolver = "2"
